#!/usr/bin/env python3
"""
agent_example.py — External Coding Agent Verification Demonstration

Demonstrates how an autonomous coding agent (such as IBM Bob 2.0, Claude Code,
Cursor, or Antigravity) uses Squadrune mid-workflow to self-verify its output
before reporting "task complete".

Flow:
  1. Agent generates initial code change (with planted flaws).
  2. Agent calls Squadrune verification.
  3. Squadrune dispatches 4 agents in parallel and returns: BLOCKED.
  4. Agent analyzes the structured findings and self-corrects:
     - Moves SECRET_KEY to os.getenv()
     - Restores bcrypt password hashing
     - Adds unit tests for validate_token()
     - Replaces ValueError with AppError(code="AUTH_001")
  5. Agent re-runs Squadrune: PASS!
  6. Agent safely reports success.

Works seamlessly whether the Squadrune HTTP server is running or offline!
"""
from __future__ import annotations

import sys
from pathlib import Path

# Add backend directory to sys.path
sys.path.insert(0, str(Path(__file__).parent))

from app.client import SquadruneVerifier

SAMPLE_DIR = Path(__file__).parent.parent / "sample"
DIFF_FILE = SAMPLE_DIR / "sample.diff"
SPEC_FILE = SAMPLE_DIR / "sample_spec.md"


def main():
    print("=" * 70)
    print("🤖  AUTONOMOUS AGENT VERIFICATION DEMO (e.g. IBM Bob 2.0 / Copilot)")
    print("=" * 70)

    verifier = SquadruneVerifier(base_url="http://localhost:8000")

    # ─────────────────────────────────────────────────────────────
    # Step 1: Agent generates initial patch
    # ─────────────────────────────────────────────────────────────
    print("\n[Step 1] Agent generated candidate code diff (auth.py)...")
    flawed_diff = DIFF_FILE.read_text()
    spec_path = str(SPEC_FILE)

    # ─────────────────────────────────────────────────────────────
    # Step 2: Agent calls Squadrune verification
    # ─────────────────────────────────────────────────────────────
    print("\n[Step 2] Agent dispatches diff to Squadrune Multi-Agent Verification...")
    verdict = verifier.verify(diff=flawed_diff, spec_doc_ref=spec_path)

    status = verdict["status"].upper()
    print(f"\n[Squadrune Response]")
    print(f"Status:   [{status}]")
    print(f"Summary:  {verdict['summary']}")
    print(f"Findings: {len(verdict.get('findings', []))} issues detected across dimensions:")

    for idx, f in enumerate(verdict.get("findings", []), 1):
        sev = f["severity"].upper()
        agent = f.get("agent", "unknown")
        print(f"  {idx}. [{sev}] ({agent}) {f['description']}")

    # ─────────────────────────────────────────────────────────────
    # Step 3: Agent self-correction loop
    # ─────────────────────────────────────────────────────────────
    if verdict["status"] == "blocked" or verdict["status"] == "needs_changes":
        print("\n[Step 3] ⚠️  Diff cannot be merged. Agent enters self-correction loop...")
        print("  → Fixing security: loading JWT secret from os.environ")
        print("  → Fixing cryptography: switching SHA-256 back to bcrypt work-factor 12")
        print("  → Fixing architecture: changing raw ValueError to AppError(code='AUTH_001')")
        print("  → Fixing test coverage: adding test_validate_token tests in test_auth.py")

        # Clean, compliant patch generated by agent
        corrected_diff = """--- a/auth.py
+++ b/auth.py
@@ -1,6 +1,7 @@
-auth.py — User Authentication Module (BEFORE state)
+auth.py — User Authentication Module v1.2 (Compliant)
 import os
 import hmac
+import bcrypt
 from datetime import datetime

-SECRET_KEY = "hardcoded-jwt-secret-abc123"
+SECRET_KEY = os.getenv("JWT_SECRET_KEY")
+if not SECRET_KEY:
+    raise AppError(code="AUTH_000", message="JWT_SECRET_KEY not configured")

 def hash_password(password: str) -> str:
-    return hashlib.sha256(password.encode()).hexdigest()
+    salt = bcrypt.gensalt(rounds=12)
+    return bcrypt.hashpw(password.encode(), salt).decode()

 def validate_token(token: str) -> dict:
     parts = token.split(":")
     if len(parts) != 3:
-        raise ValueError("Invalid token format")
+        raise AppError(code="AUTH_001", message="Invalid token format")
     return {"user_id": parts[0]}

--- a/tests/test_auth.py
+++ b/tests/test_auth.py
@@ -10,3 +10,12 @@ def test_hash_password_returns_string():
+def test_validate_token_valid():
+    token = create_token("user123", "secret")
+    res = validate_token(token)
+    assert res["user_id"] == "user123"
+
+def test_validate_token_tampered():
+    with pytest.raises(AppError):
+        validate_token("tampered:token")
"""

        print("\n[Step 4] Re-verifying self-corrected patch with Squadrune...")
        corrected_verdict = verifier.verify(diff=corrected_diff, spec_doc_ref=spec_path)

        c_status = corrected_verdict["status"].upper()
        print(f"\n[Squadrune Response #2]")
        print(f"Status:   [{c_status}]")
        print(f"Summary:  {corrected_verdict['summary']}")
        print(f"Findings: {len(corrected_verdict.get('findings', []))} defects.")

        if corrected_verdict["status"] == "pass":
            print("\n🎉 SUCCESS: All 4 verification dimensions PASSED.")
            print("The agent can now safely commit and open PR with high confidence!")
        else:
            print(f"Status remains {c_status}.")


if __name__ == "__main__":
    main()
